// Application
export const INITIALIZATION_REQUESTED = 'INITIALIZATION_REQUESTED';
export const INITIALIZATION_SUCCEEDED = 'INITIALIZATION_SUCCEEDED';
export const INITIALIZATION_FAILED = 'INITIALIZATION_FAILED';

// Customer
export const SET_CUSTOMER = 'SET_CUSTOMER';

// Deal
export const SET_DEAL = 'SET_DEAL';

// Scenario
export const UPDATE_SCENARIO = 'UPDATE_SCENARIO';
export const UPDATE_SCENARIO_REQUESTED = 'UPDATE_SCENARIO_REQUESTED';
export const UPDATE_SCENARIO_SUCCEEDED = 'UPDATE_SCENARIO_SUCCEEDED';
export const UPDATE_SCENARIO_FAILED = 'UPDATE_SCENARIO_FAILED';
export const UPDATE_SCENARIO_DETAILS = 'UPDATE_SCENARIO_DETAILS';
export const UPDATE_SCENARIO_TRADE = 'UPDATE_SCENARIO_TRADE';
export const UPDATE_SCENARIO_TYPE_REQUESTED = 'UPDATE_SCENARIO_TYPE_REQUESTED';
export const UPDATE_SCENARIO_TYPE_SUCCEEDED = 'UPDATE_SCENARIO_TYPE_SUCCEEDED';
export const UPDATE_SCENARIO_TYPE_FAILED = 'UPDATE_SCENARIO_TYPE_FAILED';
export const UPDATE_GROSS_DISPLAY_STATUS = 'UPDATE_GROSS_DISPLAY_STATUS';
export const UPDATE_SCENARIO_PROFIT_BREAKDOWN = 'UPDATE_SCENARIO_PROFIT_BREAKDOWN';
export const GET_SCENARIO_PROFIT_BREAKDOWN_REQUESTED = 'GET_SCENARIO_PROFIT_BREAKDOWN_REQUESTED';
export const GET_SCENARIO_PROFIT_BREAKDOWN_SUCCEEDED = 'GET_SCENARIO_PROFIT_BREAKDOWN_SUCCEEDED';
export const GET_SCENARIO_PROFIT_BREAKDOWN_FAILED = 'GET_SCENARIO_PROFIT_BREAKDOWN_FAILED';

// Negotiation
export const SET_NEGOTIATION_STATUS ='SET_NEGOTIATION_STATUS';
export const SET_NEGOTIATION_STATUS_REQUESTED ='SET_NEGOTIATION_STATUS_REQUESTED';
export const SET_NEGOTIATION_STATUS_SUCCEEDED ='SET_NEGOTIATION_STATUS_SUCCEEDED';
export const SET_NEGOTIATION_STATUS_FAILED ='SET_NEGOTIATION_STATUS_FAILED';
export const GET_NEGOTIATION_STATUS_REQUESTED ='GET_NEGOTIATION_STATUS_REQUESTED';
export const GET_NEGOTIATION_STATUS_SUCCEEDED ='GET_NEGOTIATION_STATUS_SUCCEEDED';
export const GET_NEGOTIATION_STATUS_FAILED ='GET_NEGOTIATION_STATUS_FAILED';
export const SET_NEGOTIATION_COUNTER_SCENARIO = 'SET_NEGOTIATION_COUNTER_SCENARIO';


// Rates and Residuals
export const INITIALIZE_RR_REQUESTED = 'INITIALIZE_RR_REQUESTED';
export const INITIALIZE_RR_SUCCEEDED = 'INITIALIZE_RR_SUCCEEDED';
export const INITIALIZE_RR_FAILED = 'INITIALIZE_RR_FAILED';
export const RETRIEVE_RR_PROGRAMS_REQUESTED = 'RETRIEVE_RR_PROGRAMS_REQUESTED';
export const RETRIEVE_RR_PROGRAMS_SUCCEEDED = 'RETRIEVE_RR_PROGRAMS_SUCCEEDED';
export const RETRIEVE_RR_PROGRAMS_FAILED = 'RETRIEVE_RR_PROGRAMS_FAILED';
export const SET_RR_PROGRAMS = 'SET_RR_PROGRAMS';
export const SET_RR_LENDERS = 'SET_RR_LENDERS';
export const SET_RR_SELECTED_LENDER = 'SET_RR_SELECTED_LENDER';
export const RETRIEVE_RR_INCENTIVES_REQUESTED = 'RETRIEVE_RR_INCENTIVES_REQUESTED';
export const RETRIEVE_RR_INCENTIVES_SUCCEEDED = 'RETRIEVE_RR_INCENTIVES_SUCCEEDED';
export const RETRIEVE_RR_INCENTIVES_FAILED = 'RETRIEVE_RR_INCENTIVES_FAILED';
export const SET_RR_INCENTIVES = 'SET_RR_INCENTIVES';
export const UPDATE_SCENARIO_FROM_RR_REQUESTED = 'UPDATE_SCENARIO_FROM_RR_REQUESTED';
export const UPDATE_SCENARIO_FROM_RR_SUCCEEDED = 'UPDATE_SCENARIO_FROM_RR_SUCCEEDED';
export const UPDATE_SCENARIO_FROM_RR_FAILED = 'UPDATE_SCENARIO_FROM_RR_FAILED';
export const SET_RR_SELECTED_PROGRAM = 'SET_RR_SELECTED_PROGRAM';
export const SET_RR_SELECTED_INCENTIVES = 'SET_RR_SELECTED_INCENTIVES';

