// Loadings
export const LOADING = 'LOADING';
export const LOADING_COMPLETE = 'LOADING_COMPLETE';

// Loading Indicator
export const LOADING_INDICATOR_START = 'LOADING_INDICATOR_START';
export const LOADING_INDICATOR_SET_PERCENT = 'LOADING_INDICATOR_SET_PERCENT';

export const FETCH_EXISTING_FEE_QUOTE_FEE_SUCCESS =
  "FETCH_EXISTING_FEE_QUOTE_FEE_SUCCESS";
export const HANDLE_CHANGE_FROM_FORM = "HANDLE_CHANGE_FROM_FORM";
export const HANDLE_CHANGE_FROM_INPUT = "HANDLE_CHANGE_FROM_INPUT";
export const HANDLE_BLUR_FROM_INPUT = "HANDLE_BLUR_FROM_INPUT";
export const DELETE_FEE = "DELETE_FEE";
export const APPEND_FEE = "APPEND_FEE";
export const REFRESH_FORM = "REFRESH_FORM";
export const CANCEL_EDITING = "CANCEL_EDITING";
export const VALIDATE_QUOTE_FEES = "VALIDATE_QUOTE_FEES";
export const SAVE_QUOTE_FEES = "SAVE_QUOTE_FEES";
