/**
 * Created by RBANDERSON on 10/5/2017.
 */
export const OFFER_IN_PROGRESS = 'OFFER_IN_PROGRESS';
export const WAITING_FOR_RESPONSE = 'WAITING_FOR_RESPONSE';
export const COUNTER_OFFER_RECEIVED = 'COUNTER_OFFER_RECEIVED';
export const OFFER_ACCEPTED = 'OFFER_ACCEPTED';
